all:
  children:

    routers:
      hosts:
        Router0:
          ansible_host: 192.168.10.254     // This host was picked because ansible needs to enter through an interface. It cant be g0/2 because its the router link so I picked the first vlan.

        Router1:
          ansible_host: 172.168.10.254

      switches:
        hosts:
          Switch0:
            ansible_host: [placeholder_ip]     // In this lab no IP was assigned to the switches so I added a placeholder, it would have to be on VLAN 10 or 20. Example IP would be 192.168.10.253.

          Switch1:
            ansible_host: [placeholder_ip]     // In this lab no IP was assigned to the switches so I added a placeholder, it would have to be on VLAN 30 or 40. Example IP would be 172.168.10.253.

 vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
            
